-- SEED PROPERTIES

-- !!!                                                                                           !!!
-- !!!            DO NOT EVER ACCIDENTALLY RUN THIS FILE IN YOUR PRODUCTION DATABASE             !!!
-- !!!    this is meant for running locally to seed your database for contributing purposes      !!!

-- create properties
INSERT INTO public.properties (
  id,
  name,
  address,
  property_type,
  purchase_date,
  purchase_price,
  current_value,
  square_meters,
  bedrooms,
  bathrooms,
  year_built,
  description,
  status,
  image_urls,
  created_at,
  updated_at,
  created_by
)
VALUES 
  (
    uuid_generate_v4(),
    'Modern Downtown Apartment',
    '123 Main St, New York, NY 10001',
    'apartment',
    '2023-06-15',
    750000.00,
    825000.00,
    85,
    2,
    2.0,
    2015,
    'Luxurious downtown apartment with city views',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  ),
  (
    uuid_generate_v4(),
    'Suburban Family Home',
    '456 Oak Ave, Boston, MA 02108',
    'residential',
    '2022-03-10',
    950000.00,
    1020000.00,
    250,
    4,
    3.0,
    1995,
    'Spacious family home in quiet neighborhood',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  ),
  (
    uuid_generate_v4(),
    'Beachfront Villa',
    '789 Ocean Dr, Miami, FL 33139',
    'villa',
    '2023-09-20',
    1200000.00,
    1350000.00,
    300,
    5,
    4.0,
    2010,
    'Stunning beachfront property with private access',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  ),
  (
    uuid_generate_v4(),
    'Commercial Office Space',
    '321 Business Blvd, Chicago, IL 60601',
    'commercial',
    '2022-11-05',
    2500000.00,
    2750000.00,
    500,
    0,
    4.0,
    2005,
    'Prime office space in business district',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  ),
  (
    uuid_generate_v4(),
    'Mountain View Cabin',
    '555 Forest Rd, Denver, CO 80202',
    'cabin',
    '2023-01-15',
    450000.00,
    495000.00,
    120,
    2,
    1.5,
    2018,
    'Cozy cabin with breathtaking mountain views',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  ),
  (
    uuid_generate_v4(),
    'Historic Brownstone',
    '888 Heritage Ln, Philadelphia, PA 19103',
    'residential',
    '2022-07-30',
    1800000.00,
    1980000.00,
    350,
    6,
    4.5,
    1890,
    'Beautifully restored historic brownstone',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  ),
  (
    uuid_generate_v4(),
    'Tech Hub Office',
    '444 Innovation Way, San Francisco, CA 94105',
    'commercial',
    '2023-03-25',
    3500000.00,
    3850000.00,
    800,
    0,
    6.0,
    2020,
    'Modern office space in tech district',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  ),
  (
    uuid_generate_v4(),
    'Luxury Penthouse',
    '777 Sky Tower, Los Angeles, CA 90001',
    'apartment',
    '2023-08-10',
    2800000.00,
    3080000.00,
    200,
    3,
    3.5,
    2018,
    'Stunning penthouse with panoramic city views',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  ),
  (
    uuid_generate_v4(),
    'Rental Property',
    '999 Investment Ave, Austin, TX 78701',
    'residential',
    '2022-05-20',
    650000.00,
    715000.00,
    180,
    3,
    2.0,
    2000,
    'Well-maintained rental property in growing area',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  ),
  (
    uuid_generate_v4(),
    'Vacation Home',
    '222 Paradise Pl, Honolulu, HI 96815',
    'residential',
    '2023-04-05',
    1500000.00,
    1650000.00,
    220,
    4,
    3.0,
    2015,
    'Beautiful vacation home near the beach',
    'active',
    ARRAY[]::TEXT[],
    current_timestamp,
    current_timestamp,
    (SELECT id FROM auth.users WHERE email = 'test@test.com')
  );